spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


server.port=${PORT:8081}


llm.api.url=https://api.groq.com/openai/v1/chat/completions
llm.api.key=${LLM_API_KEY}
llm.model=llama-3.3-70b-versatile
